services:
  nginx_inception:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    image: nginx_inception
    ports:
      - "443:443"

  mariadb_inception:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb_inception
    networks:
      - net_inception
    volumes:
      - db_website_files:/var/lib/mysql

  wordpress_inception:
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    image: wordpress_inception
    networks:
      - net_inception
    volumes:
      - db_wordpress:/var/www/html/

# A volume that contains your WordPress database.
# A second volume that contains your WordPress website files.
volumes:
  db_wordpress:
    driver: local # cleary define
  db_website_files:
    driver: local # cleary define

# A docker-network that establishes the connection between your containers.(Aってことは、1つってことか？)
networks:
  net_inception:
    driver: bridge # cleary define
