services:
### MariaDBコンテナの設定 ###
  mariadb_inception:
    restart: always
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      args:
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER1=${MARIADB_USER1}
        - MARIADB_USER1_PASSWORD=${MARIADB_USER1_PASSWORD}
    image: mariadb_inception
    networks:
      - net_inception
    volumes:
      - db_website_files:/var/lib/mysql
    init: true
    healthcheck: # ヘルスチェックを行うことで、wordpressコンテナがmariadbコンテナに接続できる状況にしておく
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost"] #MariaDBが起動していれば常に成功するコマンド
      interval: 5s
      retries: 5

### WordPressコンテナの設定 ###
  wordpress_inception:
    restart: always
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
      args:
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
    image: wordpress_inception
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_HOST_NAMEONLY=${WORDPRESS_DB_HOST_NAMEONLY}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_URL=${WORDPRESS_URL}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_EDITOR_USER=${WORDPRESS_EDITOR_USER}
      - WORDPRESS_EDITOR_PASSWORD=${WORDPRESS_EDITOR_PASSWORD}
    networks:
      - net_inception
    volumes:
      - db_wordpress:/var/www/html/
    init: true
    depends_on:
      mariadb_inception:
        condition: service_healthy # mariadbが正常に動作している場合にのみwordpressを起動。逆になると、wordpressの初期設定でDBに接続できないエラーになる。

### nginxコンテナの設定 ###
  nginx_inception:
    restart: always
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    image: nginx_inception
    networks:
      - net_inception
    volumes:
      - db_wordpress:/var/www/html/
    ports:
      - "443:443"
    init: true
    depends_on:
      - wordpress_inception

# A volume that contains your WordPress database.
# A second volume that contains your WordPress website files.
volumes:
  db_wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR_WORDPRESS} # デプロイでは/home/sotanaka/dataに変更
      o: bind
  db_website_files:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR_MARIADB} # 同上
      o: bind

# A docker-network that establishes the connection between your containers.(Aってことは、1つってことか？)
networks:
  net_inception:
    driver: bridge # cleary define
