# the containers must be built either from the penultimate stable version of Alpine or Debian.
# https://hub.docker.com/_/debian
FROM debian:12.5-slim

# A Docker container that contains MariaDB only without nginx.
# A volume that contains your WordPress database.(.yml?)

# For verify command
CMD ["sleep", "infinity"]