# the containers must be built either from the penultimate stable version of Alpine or Debian.
# https://hub.docker.com/_/debian
FROM debian:12.5-slim

# For verify command
CMD ["sleep", "infinity"]

# A Docker container that contains WordPress + php-fpm (it must be installed and configured)
# only without nginx.