services:
  web:
    build: .
    ports:
      - "8100:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}