# the containers must be built either from the penultimate stable version of Alpine or Debian.
# https://hub.docker.com/_/debian
FROM debian:12.5-slim

# A Docker container that contains NGINX with TLSv1.2 or TLSv1.3 only.
