services:
  web1:
    build: .
    ports:
      - "8100:5000"
    volumes:
      - .:/app
    depends_on:
      - web2
    networks:
      - my_network

  web2:
    build: .
    command: python app2.py
    volumes:
      - .:/app
    networks:
      - my_network

networks:
  my_network: