version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"]
      interval: 10s
      retries: 5

  wordpress:
    build: 
      context: .
      args:
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_URL: ${WORDPRESS_URL}
        WORDPRESS_TITLE: ${WORDPRESS_TITLE}
        WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
        WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
        WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 8080:80

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8100:80
    depends_on:
      - wordpress

volumes:
  db_data: {}
  wordpress_data: {}
