# 
# docker-compose.ymlファイルは、コンテナを立ち上げる時の複雑な設定をまとめて書いておけるファイル。
# 例えば、volumeのマウントや、複数コンテナの立ち上げと、ネットワーク構築など
# 

version: '3'
services: 
  mysql000ex11: 
    image: mysql:5.7
    networks: 
      - wordpress000net1
    volumes: 
      - mysql000vol11:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wordpress000db
      MYSQL_USER: wordpress000kun
      MYSQL_PASSWORD: wkunpass
  wordpress000ex12: 
    depends_on: 
      - mysql000ex11
    image: wordpress
    networks:
      - wordpress000net1
    volumes:
      - wordpress000vol12:/var/www/html
    ports:
      - 8085:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql000ex11
      WORDPRESS_DB_NAME: wordpress000db
      WORDPRESS_DB_USER: wordpress000kun
      WORDPRESS_DB_PASSWORD: wkunpass
networks:
  wordpress000net1: 
volumes: 
  mysql000vol11: 
  wordpress000vol12:
